### ISSUE TITLE
Firmament: Fast, Centralized Cluster Scheduling at Scale

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/papers-notebook#4]
https://www.usenix.org/system/files/conference/osdi16/osdi16-gog.pdf

IT IS REALLY COOL!! 同样是 OSDI 2016 的文章

**Comment by at15** [comment]
...

**Comment by gaocegege** [comment]
你不服??

**Comment by gaocegege** [comment]
Closed by https://github.com/gaocegege/papers-notebook/commit/5c50a2bb232b5ad17a83251c8200ff1232c9437f
